myblog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#应用的名称
app_name = 'blog'

urlpatterns = [
   path('article-list/', views.article_list, name='article_list'),
   path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
   path('article-create/', views.article_create, name='article_create'),
   path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
   path('article-update/<int:id>/', views.article_update, name='article_update'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #评论
    path('comment/', include('comment.urls', namespace='comment'))
]

myblog/userprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#应用的名称
app_name = 'userprofile'

urlpatterns = [
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('register/', views.user_register, name='register'),
   #用户信息
   path('edit/<int:id>/', views.user_edit, name='edit'),
]

myblog/userprofile/models.py
from django.db import models


from django.db import models
from django.contrib.auth.models import User


# 用户扩展信息
class Profile(models.Model):
    # 与 User 模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 电话号码字段
    phone = models.CharField(max_length=20, blank=True)
    # 头像

    #个人邮箱
    email = models.EmailField(blank=True)
    #头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)

    class Meta:
        db_table = 'Myprofile'

    def __str__(self):
        return 'user {}'.format(self.user.username)

myblog/userprofile/forms.py
#引入表单类
from django import forms
#引入User模型
from django.contrib.auth.models import User


#引入Profile模型
from .models import Profile
#登录表单,继承了forms.Form类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


#用户注册
class UserRegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email',)

    #对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("密码不一致,请重新输入.")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'email', 'avatar', 'bio')

myblog/userprofile/views.py
from django.shortcuts import render, redirect

from .forms import UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

# 引入 UserRegisterForm 表单类
from .forms import UserLoginForm, UserRegisterForm

from django.contrib.auth.models import User
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required


from .forms import ProfileForm

from .models import Profile
#用户登录
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            #.cleaned_data清洗出合法数据
            data = user_login_form.cleaned_data
            #检验账号,密码是否正确匹配数据库中的某个用户
            #如果均匹配则返回这个user对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                #将用户数据保存在session中,即实现了登录动作
                login(request, user)
                return redirect('blog:article_list')
            else:
                return HttpResponse('账号或者密码输入有误,请重新登录.')
        else:
            return HttpResponse('账号或者密码输入不合法')
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form': user_login_form}
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse('请使用GET或者POST请求数据.')

#用户退出
def user_logout(request):
    logout(request)
    return redirect("blog:article_list")



# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("blog:article_list")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


#用户删除
"""
@login_required是一个Python装饰器。
装饰器可以在不改变某个函数内容的前提下，给这个函数添加一些功能。
具体来说就是@login_required要求调用user_delete()函数时，用户必须登录；如果未登录则不执行函数，将页面重定向到/userprofile/login/地址去
"""
@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    user = User.objects.get(id=id)
    #验证登录用户,待删除用户是否相同
    if request.user == user:
        #退出登录
        logout(user)
        user.delete()
        return redirect('blog:article_list')
    else:
        return HttpResponse('你没有删除操作的权限')


#编辑用户信息
@login_required(login_url='/userprofile/login/')
def user_edit(request, id):
    user = User.objects.get(id=id)
    # user_id 是 OneToOneField 自动生成的字段
    if Profile.objects.filter(user_id=id).exists():
       profile = Profile.objects.get(user_id=id)
    else:
       profile = Profile.objects.create(user=user)
    if request.method == 'POST':
        if request.user != user:
            return HttpResponse('你没有权限修改此用户信息')
        profile_form = ProfileForm(data=request.POST)
        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.email = profile_cd['email']
            profile.bio = profile_cd['bio']
            profile.save()
            #带参数的redirect()
            return redirect('userprofile:edit', id=id)
        else:
            return HttpResponse('注册表单输入有误.请重新输入~')

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {'profile_form': profile_form, 'profile': profile}
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse('请使用GET或者POST请求数据')

myblog/templates/userprofile/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- email -->
                <div class="form-group col-md-4">
                    <label for="email">邮箱</label>
                    <input type="text" class="form-control" id="email" name="email" value="{{ profile.email }}">
                </div>

                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

myblog/templates/userprofile/login.html
{% extends "base.html" %}
{% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="name">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="password">
                </div>

                <div class="form-group col-md-4">
                <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-secondary">提交</button>
                </div>
            </form>
        </div>
    </div>



    <div class="col-12">
        <br>
        <h5>还没有账号？</h5>
        <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
        <br>
        <form method="post" action=".">
            ...
        </form>
    </div>
</div>



{% endblock content %}

myblog/templates/userprofile/register.html
{% extends "base.html" %}
{% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    {#
    <div class="row">#}
        {#
        <div class="col-12">#}
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username"  placeholder="必填" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="必填" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" placeholder="必填" required>
                </div>
                <!-- 提交按钮 -->
                <div class="form-group col-md-4">

                    <button type="submit" class="btn btn-secondary">提交</button>
                </div>
            </form>
{#        </div>#}
{#    </div>#}
</div>
{% endblock content %}