myblog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#应用的名称
app_name = 'blog'

urlpatterns = [
   path('article-list/', views.article_list, name='article_list'),
   path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
   path('article-create/', views.article_create, name='article_create'),
   path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
   path('article-update/<int:id>/', views.article_update, name='article_update'),
]

myblog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    #发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),

    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),

    #删除评论
    path('delete-comment/<int:id>/', views.deletet_comment, name='delete_comment')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #评论
    path('comment/', include('comment.urls', namespace='comment'))
]

myblog/userprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#应用的名称
app_name = 'userprofile'

urlpatterns = [
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('register/', views.user_register, name='register'),
   #用户信息
   path('edit/<int:id>/', views.user_edit, name='edit'),
]

myblog/blog/models.py
from django.db import models
#导入内建的User模型
from django.contrib.auth.models import User
#timezone用于处理时间相关事务
from django.utils import timezone
from django.urls import reverse

#Django-taggit 处理多对多关系的管理器
from taggit.managers import TaggableManager


from ckeditor.fields import RichTextField
class ArticleColumn(models.Model):
    """
    文章分类的Model
    """
    #栏目的标题
    title = models.CharField(max_length=100, blank=True)
    #创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePosts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, max_length=20)
    # 增加文章栏目的"一对多"外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article',
    )
    #文章标签
    tags = TaggableManager(blank=True)

    title = models.CharField(max_length=128)
    body = models.TextField()
    created_time = models.DateTimeField(default=timezone.now)
    updated_time = models.DateTimeField(auto_now=True)
    # tags = models.CharField(max_length=20)
    total_views = models.PositiveIntegerField(default=0)

    #内部类Meta中的ordering 根据字段定义了数据的排列顺序
    class Meta:
        ordering = ('-created_time',)

    def __str__(self):
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        #通过reverse()方法返回文章详情页面的url，实现了路由重定向。
        return reverse('blog:article_detail', args=[self.id])

myblog/blog/forms.py
#引入表单类
from django import forms
from.models import ArticlePosts
#引入文章模型

#写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        #指明数据模型来源
        model = ArticlePosts
        #定义表单包含的类型
        fields = ('title', 'body', 'tags')

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string

from django.http import HttpResponse

from .models import ArticlePosts
import markdown
from .forms import ArticlePostForm
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

#引入Q对象
from django.db.models import Q


#引入分页模块
from django.core.paginator import Paginator
from comment.models import Comment

from .models import ArticleColumn
#引入评论表单
from comment.forms import CommentForm
#文章列表
def article_list(request):

    search = request.GET.get('search')
    order = request.GET.get('order')
    if search:
        if order == 'total_views':
            article_list = ArticlePosts.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePosts.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        #将search参数重置为空
        search = ''
        if order == 'total_views':
            article_list = ArticlePosts.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePosts.objects.all()

    #每页显示10篇
    paginator = Paginator(article_list, 10)
    #获取url中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)
    #把order也传递进context,将search也传递进context.(传递这两个参数是为了a的href,可以看一下list.html)
    context = {'articles': articles, 'order': order, 'search': search}
    return render(request, 'blog/list.html', context)

#文章详情页
def article_detail(request, id):
    #取出响应的文章
    article = ArticlePosts.objects.get(id=id)

    #浏览量+1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 将markdown语法渲染成html样式
    md = markdown.Markdown(
         extensions=[
             # 包含 缩写、表格等常用扩展
             'markdown.extensions.extra',
             # 语法高亮扩展
             'markdown.extensions.codehilite',
             #目录
             'markdown.extensions.toc',
         ])
    #用convert()方法将正文渲染为html页面
    article.body = md.convert(article.body)
    #需要传递给末班的额对象

    #取出文章评论
    comments = Comment.objects.filter(article=id)

    #引入评论表单
    comment_form = CommentForm()

    context = {
            'article': article,
            'toc': md.toc,
            'comments': comments,
            'comment_form': comment_form,
    }
    return render(request, 'blog/detail.html', context)

#写文章视图
@login_required(login_url='/userprofile/login/')
def article_create(request):
    #判断用户是否提交数据
    if request.method == 'POST':
        #将提交的数据复制到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        #判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            #保留数据,但是不提交到数据库中
            new_article = article_post_form.save(commit=False)
            #指定目前登录的用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            # 新增的代码
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            #将新文章报窜到数据库中
            new_article.save()

            # 新增代码，保存 tags 的多对多关系
            article_post_form.save_m2m()
            return redirect('blog:article_list')
        else:
            return HttpResponse('表单内容有误,请重新填写')
    #如果用户请求获取数据
    else:
        #创建表单类实例
        article_post_form = ArticlePostForm()
        #赋值上下文
        columns =ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns': columns}
        return render(request, 'blog/create.html', context)


# 删文章
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = ArticlePosts.objects.get(id=id)
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("blog:article_list")

#更新文章
def article_update(request, id):
    # 判断用户是否提交数据
    article = ArticlePosts.objects.get(id=id)
    if request.method == 'POST':
        # 将提交的数据赋值
        article_post_form =ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            #保存新写入的文章
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.tags.set(request.POST['tags'],clear=True)

            if request.POST['column'] !='none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            # 将修改后的文章保存到数据库中
            article.save()
            # # 新增代码，保存 tags 的多对多关系
            # article_post_form.save_m2m()
            #完成后返回修改的页面.需要传入问斩的id
            return redirect('blog:article_detail', id=id)
        #如果数据不合法,则返回
        else:
            return HttpResponse('表单内容有误,请重新填写')
    # 如果用户GET请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文,将article文章对象也传递进来
        columns = ArticleColumn.objects.all()

        context = {'article': article, 'article_post_form': article_post_form, 'columns': columns}
        #将响应返回到模板
        return render(request, 'blog/update.html', context)

myblog/templates/blog/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static%}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
                <form method="post" action=".">
                    <!-- Django中需要POST数据的地方都必须有csrf_token -->
                    {% csrf_token %}
                    <!-- 文章标题 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="title">文章标题</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>

                    <!-- 文章标签 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="title">文章标签</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" placeholder="文章标签" id="tags" name="tags">
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>




</div>
{% endblock content %}

myblog/templates/blog/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>

            <ul class="col-12 alert alert-success">作者: {{ article.author }}  标签: {{ article.tags }}  创建时间: {{ article.created_time|date:"Y-m-d H:i:s" }}
                {% if user == article.author  %}
                    <a href="#" onclick="confirm_delete()" style="color:black">删除文章</a>

                    <a href="{% url 'blog:article_update' article.id %}" style="color:black">修改文章</a>
                {% endif %}
                <div>
                    浏览: {{ article.total_views }}
                </div>

            </ul>
        </div>

        <!-- 新增的目录 -->
        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>

        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>
    </div>


     <!-- 发表评论 -->
    <hr>
    {% if user.is_authenticated %}
        <div>
            <form
                action="{% url 'comment:post_comment' article.id %}"
                method="POST"
            >
            {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            我也要发言：
                        </strong>
                    </label>
                    <textarea
                        type="text"
                        class="form-control"
                        id="body"
                        name="body"
                        rows="2"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
        <br>
    {% else %}
        <br>
        <h5 class="row justify-content-center">
            请<a href="{% url 'userprofile:login' %}">登录</a>后回复
        </h5>
        <br>
    {% endif %}



    <!-- 显示评论 -->
    <h4>共有{{ comments.count }}条评论</h4>
    <div>
        {% for comment in comments %}
            <div>
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.author}}
                    </strong> 于
                    <span style="color: green">
                        {{ comment.created_time|date:"Y-m-d H:i:s" }}
                    </span> 时说：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">
                {{ comment.body }}</pre>
                <!--没有登录就不进行删除评论的操作-->
                {% if user.is_authenticated %}
                    <a href="#" style="color: #4e555b">回复评论</a>
                    <a href="{% url 'comment:delete_comment' comment.id %}" style="color: #4e555b">删除评论</a>
                {% endif %}
            </div>
        {% endfor %}
    </div>

</div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "blog:article_delete" article.id %}'
            },
        })
    }
</script>

{% endblock content %}

myblog/templates/blog/list.html
<!--继承base.html -->
{% extends "base.html" %}
{% load static %}

{% block title %}
首页
{% endblock %}

<br>
{% block content %}
<br>
<!-- 定义放置文章标题的div容器-->
<div class='container'>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'blog:article_list' %}?search={{ search }}">
                    最新
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'blog:article_list' %}?order=total_views&search={{ search }}">
                    最热
                </a>
            </li>
        </ol>
        </nav>


        <!-- 新增，搜索栏 -->
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline" >
                    <label class="sr-only">content</label>
                    <input type="text"
                        class="form-control mb-2 mr-sm-2"
                        name="search"
                        placeholder="搜索文章..."
                        required
                    >
                </form>
            </div>
        </div>

        <!-- 新增，搜索提示语 -->
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}

        {% for article in articles %}
            <div class="list-group">
                <li class="list-group-item list-group-item-action list-group-item-light">
                    <h4 class="mb-2">{{ article.title }}</h4>
                    <p class="m-1">内容摘要:{{ article.body|slice:'100' }}...</p>
                    <span>
                        <small class="col align-self-end" style="color: gray;">
                            浏览: {{ article.total_views }}
                        </small>
                    </span >

                        <a href="{%url 'blog:article_detail' article.id %}" style="color:#74787c">
                            阅读本文
                        </a>
                </li>


            </div>

        {% endfor %}

        <br><br><br>
        <!-- 页码导航 -->
        <div class="pagination row">
            <div class="m-auto">
                <span class="step-links">
                    <!-- 如果不是第一页，则显示上翻按钮 -->
                    {% if articles.has_previous %}
                        <a href="?page=1&order={{ order }}}&search={{ search }}" class="btn btn-success">
                            &laquo; 1
                        </a>
                        <span>...</span>
                        <a href="?page={{ articles.previous_page_number }}&order={{ order }}}&search={{ search }}"
                           class="btn btn-secondary"
                        >
                            {{ articles.previous_page_number }}
                        </a>
                    {% endif %}

                    <!-- 当前页面 -->
                    <span class="current btn btn-danger btn-lg">
                        {{ articles.number }}
                    </span>

                    <!-- 如果不是最末页，则显示下翻按钮 -->
                    {% if articles.has_next %}
                        <a href="?page={{ articles.next_page_number }}&order={{ order }}}&search={{ search }}"
                           class="btn btn-secondary"
                        >
                            {{ articles.next_page_number }}
                        </a>
                        <span>...</span>
                        <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}}&search={{ search }}"
                           class="btn btn-success"
                        >
                            {{ articles.paginator.num_pages }} &raquo;
                        </a>
                    {% endif %}
                </span>
            </div>
        </div>

    </div>
{% endblock %}

myblog/templates/blog/update.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 更新文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control"  id="title" name="title" value="{{ article.title }}">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标签</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" placeholder="文章标签" id="tags" name="tags">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}