myblog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#应用的名称
app_name = 'blog'

urlpatterns = [
   path('article-list/', views.article_list, name='article_list'),
   path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
   path('article-create/', views.article_create, name='article_create'),
   path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
   path('article-update/<int:id>/', views.article_update, name='article_update'),
]

myblog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    #发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),

    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),

    #删除评论
    path('delete-comment/<int:id>/', views.deletet_comment, name='delete_comment')
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #评论
    path('comment/', include('comment.urls', namespace='comment'))
]

myblog/userprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#应用的名称
app_name = 'userprofile'

urlpatterns = [
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('register/', views.user_register, name='register'),
   #用户信息
   path('edit/<int:id>/', views.user_edit, name='edit'),
]

myblog/templates/base.html
{% load static %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <!-- 引入layer.js -->
    <script src="{% static 'layer/layer.js' %}"></script>
</body>

</html>

myblog/templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>


<footer class="py-3 bg-dark fixed-bottom">

    <div class="align-items-center">

{#        <p class="text-center">友情链接:#}
{#          <button type="button" class="btn btn-outline-secondary">阿里云</button>#}
{#          <button type="button" class="btn btn-outline-secondary">网易云</button>#}
{#          <button type="button" class="btn btn-outline-secondary">腾讯云</button>#}
{#        </p>#}
    </div>
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.Jibert.com 2019</p>
    </div>
</footer>

myblog/templates/header.html
<!--定义导航栏-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">我的博客</a>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="#">首页</a> </li>
                <li class="nav-item"> <a class="nav-item nav-link" href="{% url 'blog:article_list' %}">文章</a></li>
                <li class="nav-item"><a class="nav-item nav-link disabled" href="#">图片</a></li>
                <li class="nav-item"><a class="nav-item nav-link disabled" href="#">Disabled</a></li>
            </ul>

            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'blog:article_create' %}">写文章</a>
            </div>
            <div class="navbar-nav">
                    <!-- Django的 if 模板语句 -->
                    {% if user.is_authenticated %}
                        <!-- 如果用户已经登录，则显示用户名下拉框 -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              {{ user.username }}
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                                <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">个人信息</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>

                        </li>
                    <!-- 如果用户未登录，则显示 “登录” -->
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                        </li>
                    <!-- if 语句在这里结束 -->
                    {% endif %}
            </div>
        </div>
    </div>
</nav>

myblog/templates/test.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    作者：{{ article.author }}
                    {% if user == article.author %}
                        · <a href="#" onclick="confirm_delete()">删除文章</a>
                        · <a href="{% url "article:article_update" article.id %}">
                            编辑文章
                        </a>
                    {% endif %}
                </div>
                <div>
                    浏览：{{ article.total_views }}
                </div>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>


            <!-- 相邻文章导航 -->
            <br>
            <div class="row justify-content-end">
                {% if next_article %}
                <div class="col-auto mr-auto">
                    <a  href="{{ next_article.get_absolute_url }}"
                        class="btn btn-info"
                        >
                        {{ next_article.title }}
                    </a>
                </div>
                {% endif %}
            {% if pre_article %}
                <div class="col-auto">
                    <a  href="{{ pre_article.get_absolute_url }}"
                    class="btn btn-info"
                    >
                        {{ pre_article.title }}
                    </a>
                </div>
            {% endif %}
            </div>


            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                        action="{% url 'comment:post_comment' article.id %}"
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary ">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}



            <!-- 显示评论 -->
            {% load mptt_tags %}
            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
                <!-- 遍历树形结构 -->
                {% recursetree comments %}
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                            id="comment_elem_{{ comment.id }}"
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong>

                                <!-- 显示被回复人 -->
                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right"
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong>
                                {% endif %}

                            </p>
                            <div>{{ comment.body|safe }}</div>

                            <div>
                                <span style="color: gray">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                <!-- 加载 modal 的按钮 -->
                                {% if user.is_authenticated %}
                                    <button type="button"
                                            class="btn btn-light btn-sm text-muted"
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                    >
                                        回复
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted"
                                        href="{% url 'userprofile:login' %}"
                                    >
                                        回复
                                    </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade"
                                 id="comment_{{ comment.id }}"
                                 tabindex="-1"
                                 role="dialog"
                                 aria-labelledby="CommentModalCenter"
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>

                    {% endwith %}
                {% endrecursetree %}
            </div>
        </div>

        <!-- 目录 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 粘性侧边栏样式 -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

{% block script %}
<!-- 粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

<!-- Ckeditor自适应 -->
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>

<!-- 唤醒二级回复的 modal -->
<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' +
                article_id +
                '/' +
                comment_id +
                '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    };

    // 处理二级回复
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>
{% endblock script %}